// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVsLcn3ScEEm6zncw7LJNSdoRm0xxbCh8',
    appId: '1:369484143138:web:2f14634f54bffe671fc87b',
    messagingSenderId: '369484143138',
    projectId: 'quizzle-demo-36e5c',
    authDomain: 'quizzle-demo-36e5c.firebaseapp.com',
    storageBucket: 'quizzle-demo-36e5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08X-yf7ggVT41VBl8RbFbwrwvRxjpPhg',
    appId: '1:369484143138:android:895ddbddc36867ce1fc87b',
    messagingSenderId: '369484143138',
    projectId: 'quizzle-demo-36e5c',
    storageBucket: 'quizzle-demo-36e5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB60EYgoHFPfI92DtjusNrem3gMdCYN5R4',
    appId: '1:369484143138:ios:559c98080f82f2371fc87b',
    messagingSenderId: '369484143138',
    projectId: 'quizzle-demo-36e5c',
    storageBucket: 'quizzle-demo-36e5c.appspot.com',
    iosBundleId: 'com.example.navigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB60EYgoHFPfI92DtjusNrem3gMdCYN5R4',
    appId: '1:369484143138:ios:0b81ed4e00c0fd9d1fc87b',
    messagingSenderId: '369484143138',
    projectId: 'quizzle-demo-36e5c',
    storageBucket: 'quizzle-demo-36e5c.appspot.com',
    iosBundleId: 'com.example.navigation.RunnerTests',
  );
}
